# Generated by Django 4.2.1 on 2023-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_items_json_order_itemsjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=models.CharField(max_length=50),
        ),
    ]
